services:
  postgres:
    image: postgres:15
    container_name: event-ticketing-postgres
    environment:
      POSTGRES_DB: ticketing_system_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"  # Different port to avoid conflict with local PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - event-network

  user-service:
    build:
      context: ./services/user_service
      dockerfile: Dockerfile
    container_name: event-ticketing-user-service
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ticketing_system_dev
      JWT_SECRET_KEY: docker-super-secret-key-change-in-production
    ports:
      - "8001:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./services/user_service/app:/app/app  # For development
    networks:
      - event-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  event-network:
    driver: bridge